DROP TABLE Notice IF EXISTS;

create table Notice (
	id bigint generated by default as identity,
	mdate timestamp,
	merid varchar(255),
	mernm varchar(255),
	rdate timestamp,
	rerid varchar(255),
	rernm varchar(255),
	content varchar(255),
	hits integer not null,
	title varchar(255),
	primary key (id)
);
